-- HomeFlow / IngatlanScan Sync 09A
-- REVIEWED against the live HomeFlow Supabase schema on 2026-09-10.
--
-- Purpose:
--   Safe cloud layer for IngatlanScan field surveys.
--   Does NOT alter existing HomeFlow clients / properties / cases tables.
--
-- Do not run until the implementation phase is approved.

begin;

create table if not exists public.property_surveys (
  id uuid primary key default gen_random_uuid(),

  -- Stable ID generated by IngatlanScan on the device.
  source_local_id text not null,

  -- User who owns/synced the survey.
  user_id uuid not null references auth.users(id) on delete cascade,

  -- Optional device identifier for diagnostics/conflict display.
  device_id text,

  -- IngatlanScan data schema.
  schema_version integer not null default 6 check (schema_version > 0),

  -- Search/list fields duplicated from payload for fast HomeFlow UI.
  address text,
  city text,
  district text,
  property_type text,
  owner_name text,
  owner_phone text,
  owner_email text,
  expected_price_m numeric,
  progress smallint not null default 0 check (progress between 0 and 100),
  photo_count integer not null default 0 check (photo_count >= 0),

  -- Full lossless IngatlanScan Intake object.
  payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(payload) = 'object'),

  -- Time of the last edit on the originating device.
  source_updated_at timestamptz not null,

  -- Time the field survey was originally started.
  captured_at timestamptz,

  -- HomeFlow processing state.
  sync_status text not null default 'synced'
    check (sync_status in ('synced', 'imported', 'archived')),

  -- Filled only after controlled HomeFlow import.
  client_id uuid references public.clients(id) on delete set null,
  property_id uuid references public.properties(id) on delete set null,
  case_id uuid references public.cases(id) on delete set null,
  imported_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Idempotent sync: re-sending one survey updates the same cloud row.
  unique (user_id, source_local_id)
);

comment on table public.property_surveys is
  'IngatlanScan field-survey sync layer used by HomeFlow.';

comment on column public.property_surveys.payload is
  'Complete IngatlanScan Intake JSON. Detailed rooms, technical fields and checklist remain lossless here.';

comment on column public.property_surveys.source_updated_at is
  'Last modification time reported by the source device; used for sync/conflict decisions.';

create index if not exists property_surveys_user_updated_idx
  on public.property_surveys (user_id, updated_at desc);

create index if not exists property_surveys_user_source_updated_idx
  on public.property_surveys (user_id, source_updated_at desc);

create index if not exists property_surveys_status_updated_idx
  on public.property_surveys (sync_status, updated_at desc);

create index if not exists property_surveys_property_idx
  on public.property_surveys (property_id)
  where property_id is not null;

create index if not exists property_surveys_client_idx
  on public.property_surveys (client_id)
  where client_id is not null;

create index if not exists property_surveys_case_idx
  on public.property_surveys (case_id)
  where case_id is not null;

-- Verified to exist in the current HomeFlow database.
drop trigger if exists property_surveys_set_updated_at
  on public.property_surveys;

create trigger property_surveys_set_updated_at
before update on public.property_surveys
for each row
execute function public.update_updated_at_column();

-- No anonymous/public data access.
revoke all on table public.property_surveys
from anon, public;

grant select, insert, update, delete
on table public.property_surveys
to authenticated;

alter table public.property_surveys enable row level security;

drop policy if exists "Users read own property surveys"
  on public.property_surveys;
drop policy if exists "Users create own property surveys"
  on public.property_surveys;
drop policy if exists "Users update own property surveys"
  on public.property_surveys;
drop policy if exists "Users delete own property surveys"
  on public.property_surveys;
drop policy if exists "Admins manage all property surveys"
  on public.property_surveys;

-- Any authenticated HomeFlow account can sync/read its own surveys.
create policy "Users read own property surveys"
on public.property_surveys
for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Users create own property surveys"
on public.property_surveys
for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy "Users update own property surveys"
on public.property_surveys
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "Users delete own property surveys"
on public.property_surveys
for delete
to authenticated
using (user_id = (select auth.uid()));

-- Current HomeFlow JWT already contains user_role via the existing auth hook.
create policy "Admins manage all property surveys"
on public.property_surveys
for all
to authenticated
using ((select auth.jwt() ->> 'user_role') = 'admin')
with check ((select auth.jwt() ->> 'user_role') = 'admin');

commit;
